package com.miyagi.shashin.repository

import com.miyagi.shashin.model.Metadata
import org.springframework.data.jpa.repository.Query
import org.springframework.data.repository.CrudRepository
import org.springframework.data.repository.query.Param
import org.springframework.stereotype.Repository
import jakarta.transaction.Transactional

@Transactional
@Repository
interface SearchRepository : CrudRepository<Metadata?, String?> {
    @Query("SELECT DISTINCT m.* FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN keywordphoto kp on kp.metadata_id = m.id LEFT JOIN keyword k on kp.keyword_id = k.id WHERE (k.keyword LIKE lower('%' || :term || '%') OR m.id LIKE lower('%' || :term || '%') OR m.path LIKE lower('%' || :term || '%') OR m.title LIKE lower('%' || :term || '%') OR m.description LIKE lower('%' || :term || '%') OR m.place_name LIKE lower('%' || :term || '%') OR rl.name LIKE lower('%' || :term || '%') OR m.camera LIKE lower('%' || :term || '%') OR m.lens LIKE lower('%' || :term || '%') OR m.taken_at LIKE lower('%' || :term || '%') OR m.type LIKE lower('%' || :term || '%') OR m.original_image_height = :term OR m.original_image_width = :term OR m.original_image_width || 'x' || m.original_image_height = :term) AND m.hidden = false ORDER BY m.year DESC, m.month DESC, m.day DESC, m.time DESC LIMIT :offset, :limit", nativeQuery = true)
    fun findMetadataBySearchTerm(@Param("term") term: String, @Param("offset") offset: Int, @Param("limit") limit: Int): MutableIterable<Metadata>
    @Query("SELECT DISTINCT m.* FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN keywordphoto kp on kp.metadata_id = m.id LEFT JOIN keyword k on kp.keyword_id = k.id WHERE (k.keyword LIKE lower('%' || :term || '%') OR m.id LIKE lower('%' || :term || '%') OR m.path LIKE lower('%' || :term || '%') OR m.title LIKE lower('%' || :term || '%') OR m.description LIKE lower('%' || :term || '%') OR m.place_name LIKE lower('%' || :term || '%') OR rl.name LIKE lower('%' || :term || '%') OR m.camera LIKE lower('%' || :term || '%') OR m.lens LIKE lower('%' || :term || '%') OR m.taken_at LIKE lower('%' || :term || '%') OR m.type LIKE lower('%' || :term || '%') OR m.original_image_height = :term OR m.original_image_width = :term OR m.original_image_width || 'x' || m.original_image_height = :term) AND m.hidden = false AND taken_at >= :startDate AND taken_at <= :endDate ORDER BY m.year DESC, m.month DESC, m.day DESC, m.time DESC", nativeQuery = true)
    fun findMetadataBySearchTermByDate(@Param("startDate") startDate: String, @Param("endDate") endDate: String, @Param("term") term: String): MutableList<Metadata>?
    @Query("SELECT DISTINCT m.* FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN albumphoto a ON m.id = a.metadata_id LEFT JOIN useralbum ua ON ua.album_id = a.album_id LEFT JOIN keywordphoto kp on kp.metadata_id = a.metadata_id LEFT JOIN keyword k on kp.keyword_id = k.id WHERE (k.keyword LIKE lower('%' || :term || '%') OR m.file_name LIKE lower('%' || :term || '%') OR m.title LIKE lower('%' || :term || '%') OR m.description LIKE lower('%' || :term || '%') OR m.place_name LIKE lower('%' || :term || '%') OR rl.name LIKE lower('%' || :term || '%') OR m.camera LIKE lower('%' || :term || '%') OR m.lens LIKE lower('%' || :term || '%') OR m.taken_at LIKE lower('%' || :term || '%') OR m.type LIKE lower('%' || :term || '%') OR m.original_image_height = :term OR m.original_image_width = :term OR m.original_image_width || 'x' || m.original_image_height = :term) AND m.hidden = false AND ua.user_id = :userId ORDER BY m.year DESC, m.month DESC, m.day DESC, m.time DESC LIMIT :offset, :limit", nativeQuery = true)
    fun findMetadataBySearchTermAndUserId(@Param("term") term: String, @Param("userId") userId: Int, @Param("offset") offset: Int, @Param("limit") limit: Int): MutableIterable<Metadata>
}