package com.miyagi.shashin.repository

import com.miyagi.shashin.model.Metadata
import org.springframework.data.jpa.repository.Query
import org.springframework.data.repository.CrudRepository
import org.springframework.data.repository.query.Param
import org.springframework.stereotype.Repository
import jakarta.transaction.Transactional

@Transactional
@Repository
interface SearchRepository : CrudRepository<Metadata?, String?> {
    @Query("SELECT DISTINCT m.* FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN keywordphoto kp on kp.metadata_id = m.id LEFT JOIN keyword k on kp.keyword_id = k.id WHERE (k.keyword LIKE lower('%' || :term || '%') OR m.id LIKE lower('%' || :term || '%') OR m.path LIKE lower('%' || :term || '%') OR m.title LIKE lower('%' || :term || '%') OR m.description LIKE lower('%' || :term || '%') OR m.place_name LIKE lower('%' || :term || '%') OR rl.name LIKE lower('%' || :term || '%') OR m.camera LIKE lower('%' || :term || '%') OR m.lens LIKE lower('%' || :term || '%') OR m.taken_at LIKE lower('%' || :term || '%') OR m.type LIKE lower('%' || :term || '%') OR m.original_image_height = :term OR m.original_image_width = :term OR m.original_image_width || 'x' || m.original_image_height = :term) AND m.hidden = false ORDER BY m.year DESC, m.month DESC, m.day DESC, m.time DESC LIMIT :offset, :limit", nativeQuery = true)
    fun findMetadataBySearchTerm(@Param("term") term: String, @Param("offset") offset: Int, @Param("limit") limit: Int): MutableIterable<Metadata>
    @Query("SELECT * FROM metadata WHERE (sharpness != \"1.0\" OR saturation != \"1.0\" OR contrast != \"1.0\" OR brightness != \"1.0\" OR rotation != 0 OR flip_horizontally = true OR flip_vertically = true) AND hidden = false ORDER BY year DESC, month DESC, day DESC, time DESC LIMIT :offset, :limit", nativeQuery = true)
    fun findMetadataEditedPhotos(@Param("offset") offset: Int, @Param("limit") limit: Int): MutableIterable<Metadata>
    @Query("SELECT * FROM metadata WHERE (sharpness != \"1.0\" OR saturation != \"1.0\" OR contrast != \"1.0\" OR brightness != \"1.0\" OR rotation != 0 OR flip_horizontally = true OR flip_vertically = true) AND taken_at >= :startDate AND taken_at <= :endDate AND hidden = false ORDER BY year DESC, month DESC, day DESC, time DESC", nativeQuery = true)
    fun findMetadataEditedPhotosByDate(@Param("startDate") startDate: String, @Param("endDate") endDate: String): MutableList<Metadata>?
    @Query("SELECT DISTINCT m.* FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN albumphoto a ON m.id = a.metadata_id LEFT JOIN useralbum ua ON ua.album_id = a.album_id WHERE (m.sharpness != \"1.0\" OR m.saturation != \"1.0\" OR m.contrast != \"1.0\" OR m.brightness != \"1.0\" OR m.rotation != 0 OR m.flip_horizontally = true OR m.flip_vertically = true) AND m.hidden = false AND ua.user_id = :userId ORDER BY m.year DESC, m.month DESC, m.day DESC, m.time DESC LIMIT :offset, :limit", nativeQuery = true)
    fun findMetadataEditedPhotosAndUserId(@Param("userId") userId: Int, @Param("offset") offset: Int, @Param("limit") limit: Int): MutableIterable<Metadata>
    @Query("SELECT DISTINCT m.* FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN albumphoto a ON m.id = a.metadata_id LEFT JOIN useralbum ua ON ua.album_id = a.album_id WHERE (m.sharpness != \"1.0\" OR m.saturation != \"1.0\" OR m.contrast != \"1.0\" OR m.brightness != \"1.0\" OR m.rotation != 0 OR m.flip_horizontally = true OR m.flip_vertically = true) AND m.hidden = false AND ua.user_id = :userId AND m.taken_at >= :startDate AND m.taken_at <= :endDate ORDER BY m.year DESC, m.month DESC, m.day DESC, m.time DESC", nativeQuery = true)
    fun findMetadataEditedPhotosAndUserIdByDate(@Param("userId") userId: Int, @Param("startDate") startDate: String, @Param("endDate") endDate: String): MutableList<Metadata>?
    @Query("SELECT COUNT(DISTINCT m.id) FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN keywordphoto kp on kp.metadata_id = m.id LEFT JOIN keyword k on kp.keyword_id = k.id WHERE (k.keyword LIKE lower('%' || :term || '%') OR m.id LIKE lower('%' || :term || '%') OR m.path LIKE lower('%' || :term || '%') OR m.title LIKE lower('%' || :term || '%') OR m.description LIKE lower('%' || :term || '%') OR m.place_name LIKE lower('%' || :term || '%') OR rl.name LIKE lower('%' || :term || '%') OR m.camera LIKE lower('%' || :term || '%') OR m.lens LIKE lower('%' || :term || '%') OR m.taken_at LIKE lower('%' || :term || '%') OR m.type LIKE lower('%' || :term || '%') OR m.original_image_height = :term OR m.original_image_width = :term OR m.original_image_width || 'x' || m.original_image_height = :term) AND m.hidden = false", nativeQuery = true)
    fun countAllByHiddenIsFalse(@Param("term") term: String): Int
    @Query("SELECT DISTINCT m.* FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN keywordphoto kp on kp.metadata_id = m.id LEFT JOIN keyword k on kp.keyword_id = k.id WHERE (k.keyword LIKE lower('%' || :term || '%') OR m.id LIKE lower('%' || :term || '%') OR m.path LIKE lower('%' || :term || '%') OR m.title LIKE lower('%' || :term || '%') OR m.description LIKE lower('%' || :term || '%') OR m.place_name LIKE lower('%' || :term || '%') OR rl.name LIKE lower('%' || :term || '%') OR m.camera LIKE lower('%' || :term || '%') OR m.lens LIKE lower('%' || :term || '%') OR m.taken_at LIKE lower('%' || :term || '%') OR m.type LIKE lower('%' || :term || '%') OR m.original_image_height = :term OR m.original_image_width = :term OR m.original_image_width || 'x' || m.original_image_height = :term) AND m.hidden = false AND m.taken_at >= :startDate AND m.taken_at <= :endDate ORDER BY m.year DESC, m.month DESC, m.day DESC, m.time DESC", nativeQuery = true)
    fun findMetadataBySearchTermByDate(@Param("startDate") startDate: String, @Param("endDate") endDate: String, @Param("term") term: String): MutableList<Metadata>?
    @Query("SELECT DISTINCT m.* FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN albumphoto a ON m.id = a.metadata_id LEFT JOIN useralbum ua ON ua.album_id = a.album_id LEFT JOIN keywordphoto kp on kp.metadata_id = a.metadata_id LEFT JOIN keyword k on kp.keyword_id = k.id WHERE (k.keyword LIKE lower('%' || :term || '%') OR m.file_name LIKE lower('%' || :term || '%') OR m.title LIKE lower('%' || :term || '%') OR m.description LIKE lower('%' || :term || '%') OR m.place_name LIKE lower('%' || :term || '%') OR rl.name LIKE lower('%' || :term || '%') OR m.camera LIKE lower('%' || :term || '%') OR m.lens LIKE lower('%' || :term || '%') OR m.taken_at LIKE lower('%' || :term || '%') OR m.type LIKE lower('%' || :term || '%') OR m.original_image_height = :term OR m.original_image_width = :term OR m.original_image_width || 'x' || m.original_image_height = :term) AND m.hidden = false AND ua.user_id = :userId ORDER BY m.year DESC, m.month DESC, m.day DESC, m.time DESC LIMIT :offset, :limit", nativeQuery = true)
    fun findMetadataBySearchTermAndUserId(@Param("term") term: String, @Param("userId") userId: Int, @Param("offset") offset: Int, @Param("limit") limit: Int): MutableIterable<Metadata>
    @Query("SELECT DISTINCT m.* FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN albumphoto a ON m.id = a.metadata_id LEFT JOIN useralbum ua ON ua.album_id = a.album_id LEFT JOIN keywordphoto kp on kp.metadata_id = a.metadata_id LEFT JOIN keyword k on kp.keyword_id = k.id WHERE (k.keyword LIKE lower('%' || :term || '%') OR m.file_name LIKE lower('%' || :term || '%') OR m.title LIKE lower('%' || :term || '%') OR m.description LIKE lower('%' || :term || '%') OR m.place_name LIKE lower('%' || :term || '%') OR rl.name LIKE lower('%' || :term || '%') OR m.camera LIKE lower('%' || :term || '%') OR m.lens LIKE lower('%' || :term || '%') OR m.taken_at LIKE lower('%' || :term || '%') OR m.type LIKE lower('%' || :term || '%') OR m.original_image_height = :term OR m.original_image_width = :term OR m.original_image_width || 'x' || m.original_image_height = :term) AND m.hidden = false AND ua.user_id = :userId AND m.taken_at >= :startDate AND m.taken_at <= :endDate ORDER BY m.year DESC, m.month DESC, m.day DESC, m.time DESC", nativeQuery = true)
    fun findMetadataBySearchTermAndUserIdByDate(@Param("term") term: String, @Param("userId") userId: Int, @Param("startDate") startDate: String, @Param("endDate") endDate: String): MutableList<Metadata>?
    @Query("SELECT COUNT(DISTINCT m.id) FROM metadata m LEFT JOIN recognitionlabelphoto rlp ON m.id = rlp.metadata_id LEFT JOIN recognitionlabel rl ON rl.id = rlp.recognition_label_id LEFT JOIN albumphoto a ON m.id = a.metadata_id LEFT JOIN useralbum ua ON ua.album_id = a.album_id LEFT JOIN keywordphoto kp on kp.metadata_id = a.metadata_id LEFT JOIN keyword k on kp.keyword_id = k.id WHERE (k.keyword LIKE lower('%' || :term || '%') OR m.file_name LIKE lower('%' || :term || '%') OR m.title LIKE lower('%' || :term || '%') OR m.description LIKE lower('%' || :term || '%') OR m.place_name LIKE lower('%' || :term || '%') OR rl.name LIKE lower('%' || :term || '%') OR m.camera LIKE lower('%' || :term || '%') OR m.lens LIKE lower('%' || :term || '%') OR m.taken_at LIKE lower('%' || :term || '%') OR m.type LIKE lower('%' || :term || '%') OR m.original_image_height = :term OR m.original_image_width = :term OR m.original_image_width || 'x' || m.original_image_height = :term) AND m.hidden = false AND ua.user_id = :userId", nativeQuery = true)
    fun countAllByHiddenIsFalseAndUserId(@Param("term") term: String, @Param("userId") userId: Int): Int
}