app.js.useMinified=false
app.sidecar.path=/sidecar_test/

app.config.cron.expression.matchscan=0 0 9 * * *

spring.datasource.url=jdbc:sqlite:shashin_test.db?date_string_format=yyyy-MM-dd HH:mm:ss
