spring.profiles.active=prod

spring.sql.init.schema-locations=classpath:schema.sql
spring.cloud.compatibility-verifier.enabled=false
spring.datasource.username=shashinUser
spring.datasource.password=ENC(BK2KP4vHevVEHHNo)
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=25
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.tomcat.max-active=20
spring.datasource.tomcat.test-while-idle=true
spring.datasource.tomcat.validation-query=select 1
spring.datasource.tomcat.default-auto-commit=false
spring.datasource.tomcat.min-idle=15
spring.datasource.tomcat.initial-size=15
spring.jpa.properties.hibernate.hbm2ddl.auto=update
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# org.sqlite.hibernate.dialect.SQLiteDialect
#spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.web.resources.cache.cachecontrol.max-age=3600
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
spring.servlet.multipart.enabled=true
#spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.mvc.pathmatch.matching-strategy=ANT-PATH-MATCHER
spring.messages.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.sql.init.encoding=UTF-8
#spring.thymeleaf.cache=true

springdoc.packagesToScan=com.miyagi.shashin
springdoc.pathsToMatch=/api/v1/**

# 30 min session timeout
server.servlet.session.timeout=1800s
server.port=6624
management.endpoint.restart.enabled=true
management.endpoints.web.exposure.include=health

logging.file.name=logs/shashin.log
#logging.level.root=DEBUG
logging.level.root=INFO
logging.level.org.hibernate=ERROR
logging.logback.rollingpolicy.max-file-size=2MB
logging.logback.rollingpolicy.max-history=2

app.rememberme.key=7430689e-3db2-40e2-8853-616c0fcc0a31
app.rememberme.expiration.seconds=31536000

app.config.default.querylimit=30
app.config.default.matchscanlimit=30
app.config.default.trainingdatalimit=100
app.config.default.notificationlimit=20
app.config.default.searchhistorylimit=10
app.config.default.recognitionConfidenceThreshold=0.8
app.config.default.objectRecognitionConfidenceThreshold=0.45
app.config.default.scheduledTime=2:00
app.api.version=v1
app.role.user=ROLE_USER
app.role.admin=ROLE_ADMIN
app.role.super=ROLE_SUPER
# Load records before scrolling
app.endpoint.url.compreface=http://127.0.0.1:8000/
app.endpoint.url.geocode=https://nominatim.openstreetmap.org/
app.build.properties.version=@project.version@
app.build.properties.name=@project.name@

app.github.key=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
app.circleci.key=CCIPRJ_Xu31zj9EUnWDR3zYbb6zan_6d02ff35a38c7a5f50ed1b7e3526bd3c95354f37