spring.jpa.show-sql=true

app.js.useMinified=true
app.sidecar.path=/sidecar/

app.config.cron.expression.matchscan=0 0 9 * * *

spring.datasource.url=jdbc:sqlite:shashin.db?date_string_format=yyyy-MM-dd HH:mm:ss
