spring.jpa.show-sql=true

app.js.useMinified=true
app.sidecar.path=/sidecar/

spring.datasource.hikari.maximum-pool-size=25
spring.datasource.url=jdbc:sqlite:shashin.db?date_string_format=yyyy-MM-dd HH:mm:ss
