spring.profiles.active=@activatedProperties@

spring.datasource.username=myagi
spring.datasource.password=BK2KP4vHevVEHHNo
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.tomcat.max-active=20
spring.datasource.tomcat.test-while-idle=true
spring.datasource.tomcat.validation-query=select 1
spring.datasource.tomcat.default-auto-commit=false
spring.datasource.tomcat.min-idle=15
spring.datasource.tomcat.initial-size=15
#spring.datasource.hikari.maximum-pool-size=1
spring.sql.init.encoding=UTF-8
#spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.sqlite.hibernate.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.web.resources.cache.cachecontrol.max-age=3600
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
spring.servlet.multipart.enabled=true
#spring.thymeleaf.cache=true

# 30 min session timeout
server.servlet.session.timeout=1800s
server.port=6624
management.endpoint.restart.enabled=true
management.endpoints.web.exposure.include=restart,health

logging.level.root=INFO
#logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.logback.rollingpolicy.max-file-size=2MB
logging.logback.rollingpolicy.max-history=2

app.rememberme.key=7430689e-3db2-40e2-8853-616c0fcc0a31
app.rememberme.expiration.seconds=31536000

app.api.version=v1
app.role.user=ROLE_USER
app.role.admin=ROLE_ADMIN
# Load records before scrolling
app.endpoint.url.geocode=https://nominatim.openstreetmap.org/
app.build.properties.version=@project.version@
app.build.properties.name=@project.name@