app.js.useMinified=false
app.sidecar.path=/sidecar_test/

#logging.level.org.hibernate.SQL=DEBUG
## See param binding
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
## See transaction information
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.springframework.web=DEBUG
spring.datasource.url=jdbc:sqlite:shashin_test.db?date_string_format=yyyy-MM-dd HH:mm:ss
spring.datasource.hikari.maximum-pool-size=5