spring.datasource.url=jdbc:sqlite:shashin.db?date_string_format=yyyy-MM-dd HH:mm:ss
spring.datasource.username=
spring.datasource.password=
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8
spring.sql.init.encoding=UTF-8
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.tomcat.max-active=20
spring.datasource.tomcat.test-while-idle=true
spring.datasource.tomcat.validation-query=select 1
spring.datasource.tomcat.default-auto-commit=false
spring.datasource.tomcat.min-idle=15
spring.datasource.tomcat.initial-size=15
#spring.datasource.hikari.maximum-pool-size=1
#spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=com.miyagi.shashin.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# 30 min session timeout
server.servlet.session.timeout=1800s
server.port=9244

logging.level.root=INFO

app.rememberme.key=7430689e-3db2-40e2-8853-616c0fcc0a31
app.rememberme.expiration.seconds=86400

app.sidecar.path=/sidecar/
app.api.version=v1
app.role.user=ROLE_USER
app.role.admin=ROLE_ADMIN
# Load records before scrolling
app.endpoint.url.geocode=https://nominatim.openstreetmap.org/
# Moved to DB
#app.mediaDirs=c:/Users/micha/Downloads/shashinphotos,c:/Users/micha/Downloads/shashinvideos,c:/Users/micha/Downloads/shashinphotospeople
