version: 2.1
orbs:
  maven: circleci/maven@1.2.0
  cloudsmith: cloudsmith/cloudsmith@1.0.3

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          post-steps: # steps to run after steps defined in gradle/run
            - persist_to_workspace:
                root: .
                paths:
                  - target/shashin-1.0.0.jar
                  - target/Shashin-1.0.0.exe
            - store_artifacts:
                path: target/shashin-1.0.0.jar
                destination: shashin-1.0.0.jar
            - store_artifacts:
                path: target/Shashin-1.0.0.exe
                destination: Shashin-1.0.0.exe
            - cloudsmith/publish:
                cloudsmith-repository: michael-yagi-nYM/shashin
                package-format: maven
                package-path: target/shashin-*.jar
#            - cloudsmith/publish:
#                cloudsmith-repository: michael-yagi-nYM/shashin
#                package-format: exe
#                package-path: target/Shashin-*.exe
